/*
 * Copyright © 2025 Bithatch (tanktarta@gmail.com)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the “Software”), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// Generated by jextract

package uk.co.bithatch.linid.impl.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ip_opts {
 *     struct in_addr ip_dst;
 *     char ip_opts[40];
 * }
 * }
 */
public class ip_opts {

    ip_opts() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        in_addr.layout().withName("ip_dst"),
        MemoryLayout.sequenceLayout(40, nss_proto_h.C_CHAR).withName("ip_opts")
    ).withName("ip_opts");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ip_dst$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ip_dst"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct in_addr ip_dst
     * }
     */
    public static final GroupLayout ip_dst$layout() {
        return ip_dst$LAYOUT;
    }

    private static final long ip_dst$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct in_addr ip_dst
     * }
     */
    public static final long ip_dst$offset() {
        return ip_dst$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct in_addr ip_dst
     * }
     */
    public static MemorySegment ip_dst(MemorySegment struct) {
        return struct.asSlice(ip_dst$OFFSET, ip_dst$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct in_addr ip_dst
     * }
     */
    public static void ip_dst(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ip_dst$OFFSET, ip_dst$LAYOUT.byteSize());
    }

    private static final SequenceLayout ip_opts$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ip_opts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static final SequenceLayout ip_opts$layout() {
        return ip_opts$LAYOUT;
    }

    private static final long ip_opts$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static final long ip_opts$offset() {
        return ip_opts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static MemorySegment ip_opts(MemorySegment struct) {
        return struct.asSlice(ip_opts$OFFSET, ip_opts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static void ip_opts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ip_opts$OFFSET, ip_opts$LAYOUT.byteSize());
    }

    private static long[] ip_opts$DIMS = { 40 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static long[] ip_opts$dimensions() {
        return ip_opts$DIMS;
    }
    private static final VarHandle ip_opts$ELEM_HANDLE = ip_opts$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static byte ip_opts(MemorySegment struct, long index0) {
        return (byte)ip_opts$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char ip_opts[40]
     * }
     */
    public static void ip_opts(MemorySegment struct, long index0, byte fieldValue) {
        ip_opts$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

