// Generated by jextract

package uk.co.bithatch.linid.impl.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct pam_message {
 *     int msg_style;
 *     const char *msg;
 * }
 * }
 */
public class pam_message {

    pam_message() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        nss_proto_h.C_INT.withName("msg_style"),
        MemoryLayout.paddingLayout(4),
        nss_proto_h.C_POINTER.withName("msg")
    ).withName("pam_message");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt msg_style$LAYOUT = (OfInt)$LAYOUT.select(groupElement("msg_style"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int msg_style
     * }
     */
    public static final OfInt msg_style$layout() {
        return msg_style$LAYOUT;
    }

    private static final long msg_style$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int msg_style
     * }
     */
    public static final long msg_style$offset() {
        return msg_style$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int msg_style
     * }
     */
    public static int msg_style(MemorySegment struct) {
        return struct.get(msg_style$LAYOUT, msg_style$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int msg_style
     * }
     */
    public static void msg_style(MemorySegment struct, int fieldValue) {
        struct.set(msg_style$LAYOUT, msg_style$OFFSET, fieldValue);
    }

    private static final AddressLayout msg$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("msg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *msg
     * }
     */
    public static final AddressLayout msg$layout() {
        return msg$LAYOUT;
    }

    private static final long msg$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *msg
     * }
     */
    public static final long msg$offset() {
        return msg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *msg
     * }
     */
    public static MemorySegment msg(MemorySegment struct) {
        return struct.get(msg$LAYOUT, msg$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *msg
     * }
     */
    public static void msg(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(msg$LAYOUT, msg$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

