// Generated by jextract

package uk.co.bithatch.linid.impl.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct pam_response {
 *     char *resp;
 *     int resp_retcode;
 * }
 * }
 */
public class pam_response {

    pam_response() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        nss_proto_h.C_POINTER.withName("resp"),
        nss_proto_h.C_INT.withName("resp_retcode"),
        MemoryLayout.paddingLayout(4)
    ).withName("pam_response");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout resp$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("resp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *resp
     * }
     */
    public static final AddressLayout resp$layout() {
        return resp$LAYOUT;
    }

    private static final long resp$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *resp
     * }
     */
    public static final long resp$offset() {
        return resp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *resp
     * }
     */
    public static MemorySegment resp(MemorySegment struct) {
        return struct.get(resp$LAYOUT, resp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *resp
     * }
     */
    public static void resp(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(resp$LAYOUT, resp$OFFSET, fieldValue);
    }

    private static final OfInt resp_retcode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resp_retcode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int resp_retcode
     * }
     */
    public static final OfInt resp_retcode$layout() {
        return resp_retcode$LAYOUT;
    }

    private static final long resp_retcode$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int resp_retcode
     * }
     */
    public static final long resp_retcode$offset() {
        return resp_retcode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int resp_retcode
     * }
     */
    public static int resp_retcode(MemorySegment struct) {
        return struct.get(resp_retcode$LAYOUT, resp_retcode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int resp_retcode
     * }
     */
    public static void resp_retcode(MemorySegment struct, int fieldValue) {
        struct.set(resp_retcode$LAYOUT, resp_retcode$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

