// Generated by jextract

package uk.co.bithatch.linid.impl.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rpcent {
 *     char *r_name;
 *     char **r_aliases;
 *     int r_number;
 * }
 * }
 */
public class rpcent {

    rpcent() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        nss_proto_h.C_POINTER.withName("r_name"),
        nss_proto_h.C_POINTER.withName("r_aliases"),
        nss_proto_h.C_INT.withName("r_number"),
        MemoryLayout.paddingLayout(4)
    ).withName("rpcent");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout r_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("r_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *r_name
     * }
     */
    public static final AddressLayout r_name$layout() {
        return r_name$LAYOUT;
    }

    private static final long r_name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *r_name
     * }
     */
    public static final long r_name$offset() {
        return r_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *r_name
     * }
     */
    public static MemorySegment r_name(MemorySegment struct) {
        return struct.get(r_name$LAYOUT, r_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *r_name
     * }
     */
    public static void r_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(r_name$LAYOUT, r_name$OFFSET, fieldValue);
    }

    private static final AddressLayout r_aliases$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("r_aliases"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **r_aliases
     * }
     */
    public static final AddressLayout r_aliases$layout() {
        return r_aliases$LAYOUT;
    }

    private static final long r_aliases$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **r_aliases
     * }
     */
    public static final long r_aliases$offset() {
        return r_aliases$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **r_aliases
     * }
     */
    public static MemorySegment r_aliases(MemorySegment struct) {
        return struct.get(r_aliases$LAYOUT, r_aliases$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **r_aliases
     * }
     */
    public static void r_aliases(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(r_aliases$LAYOUT, r_aliases$OFFSET, fieldValue);
    }

    private static final OfInt r_number$LAYOUT = (OfInt)$LAYOUT.select(groupElement("r_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int r_number
     * }
     */
    public static final OfInt r_number$layout() {
        return r_number$LAYOUT;
    }

    private static final long r_number$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int r_number
     * }
     */
    public static final long r_number$offset() {
        return r_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int r_number
     * }
     */
    public static int r_number(MemorySegment struct) {
        return struct.get(r_number$LAYOUT, r_number$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int r_number
     * }
     */
    public static void r_number(MemorySegment struct, int fieldValue) {
        struct.set(r_number$LAYOUT, r_number$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

